blank_issues_enabled: true
contact_links:
  - name: Issue with documentation
    url:  https://github.com/Phoesion/Glow-Documentation/issues/new/choose
    about: Please open issues relating to Documentation in Phoesion/Glow-Documentation